# Generated by Django 6.1.1 on 2026-09-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(default=0),
        ),
    ]
