# Generated by Django 6.1.1 on 2026-09-08 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_skill_proficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cell_type', models.CharField(choices=[('markdown', 'Markdown'), ('code', 'Code')], default='markdown', max_length=10)),
                ('content', models.TextField()),
                ('language', models.CharField(default='python', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('cover_image_url', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('tags', models.ManyToManyField(related_name='blogs', to='content.tag')),
            ],
        ),
        migrations.CreateModel(
            name='BlogCellOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_output', models.TextField(blank=True, null=True)),
                ('error_output', models.TextField(blank=True, null=True)),
                ('image_output', models.TextField(blank=True, null=True)),
                ('cell', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='content.blogcell')),
            ],
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.blog')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='blogcell',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='content.blogsection'),
        ),
    ]
