# Generated by Django 6.1.1 on 2026-09-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_blogreadevent_blog'),
        ('content', '0003_blogcell_remove_blogpost_tags_blog_blogcelloutput_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
