# Generated by Django 6.1.1 on 2026-09-09 14:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_delete_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsection',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='blogsection',
            unique_together={('blog', 'slug')},
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('storage_path', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to='content.blogsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
