# Generated by Django 6.1.1 on 2026-09-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_blogsection_slug_alter_blogsection_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcelloutput',
            name='html_output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
