# Generated by Django 6.1.1 on 2026-09-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_blogcelloutput_html_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
