# Generated by Django 6.1.1 on 2026-09-08 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('content', '0003_blogcell_remove_blogpost_tags_blog_blogcelloutput_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogreadevent',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_events', to='content.blog'),
        ),
    ]
